@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300
    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

component index.js {
    class authRoutes{
        ..Подключаю router..
        const authRoutes = require('./routes/auth'); 
        ..Регистрирую router..
        app.use('/auth', authRoutes);
    }

}

package views #gray{

package auth #gray{

    component login.hbs{

    }
}

package partials #gray{
    component navbar.hbs{

    }
}
}

package public #gray{
component app.js{
    class tabs{
        ..Инициализирую tabs..
        M.Tabs.init(document.querySelectorAll('.tabs'));
    }
}
}

package routs #gray{
    class auth{
        ....
        const { Router } = require('express');
const router = Router();

module.exports = router;
....
router.get('/login', async (req, res) => {
  res.render('auth/login', {
    title: 'Авторизация',
    isLogin: true,
  });
});
    }
}
note left
    Cоздаю объект 
    router и экспортирую 
    его
    end note


index.js -up-> auth
navbar.hbs --> auth
auth -up-> login.hbs
tabs -right-> login.hbs

@enduml