@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300
    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
    ComponentBackgroundColor DarkSlateGrey
}

component index.js{
    class start{
        const express = require('express');
        const mongoose = require('mongoose');
        const session = require('express-session');
        const MongoStore = require('connect-mongodb-session')(session);
        ....
        const store = new MongoStore({
            collection: 'sessions',
            uri: keys.MONGODB_URI,}
        );
        ....
        app.use(
        session({
            secret: keys.SESSION_SECRET,
            resave: false,
            saveUninitialized: false,
            store,}
        )
        );
        ....
        const PORT = process.env.PORT || 3000;

        async function start() {
            try {
                await mongoose.connect(keys.MONGODB_URI, {
                    useNewUrlParser: true,
                    useUnifiedTopology: true,
                    useFindAndModify: false,}
                ); // это было подключение к БД

                app.listen(PORT, () => {
                    console.log(`Сервер запущен на порту ${PORT}`);}
                );}
            catch (e) {
                console.log(e);}}
        start();
    }
}

package keys{
  component keys_index.js{
class keys_prod_dev{
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./keys.prod');
} else {
  module.exports = require('./keys.dev');}
}
  }
  component keys.dev.js{
class dev{
    // keys.dev.js

module.exports = {
  MONGODB_URI:
    'mongodb+srv://konstantine899:M0HmjAaCApHdkHCl@cluster0-nijcz.mongodb.net/shop',
  SESSION_SECRET: 'some secret value',
  SENDGRID_API_KEY:
'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',
  EMAIL_FROM: '375298918971@mail.ru',
  BASE_URL: 'http://localhost:3000',
};

}
  }
  component keys.prod.js{
class prod{
    // keys.prod.js

module.exports = {
  MONGODB_URI: process.env.MONGODB_URI,
  SESSION_SECRET: process.env.SESSION_SECRET,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  BASE_URL: process.env.BASE_URL,
};

}
  }
}

database MongoDB{

}

prod <--> keys_prod_dev
dev <--> keys_prod_dev
keys_prod_dev <--> start
MongoDB <-left-> start

@enduml