@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300

    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

skinparam usecase{
    FontColor<< UC5 >> green
    FontColor<< input >> Aqua
    FontColor<< textarea >> Aqua
    BackgroundColor<< validation >> red
}

component "index.js" #gray{
    class connect__handlebars{
        const Handlebars = require('handlebars');
        const exphbs = require('express-handlebars');
        ....
        const hbs = exphbs.create({
            defaultLayout: 'main',
            extname: 'hbs',
            helpers: require('./utils/hbs-helpers'),
            handlebars: allowInsecurePrototypeAccess(Handlebars), }
        );
        app.engine('hbs', hbs.engine);
        app.set('view engine', 'hbs');
        app.set('views', 'views');}
}
}

package "views" #gray{

    package "layout" #gray{

component "main.hbs"{

}
    }


    component index.hbs{

    }
    package partials #gray{
        component footer.hbs{

        }

        component head.hbs{

        }
        component navbar.hbs{

        }
    }
    }

     package utils #gray{
        class hbshelpers{
            module.exports = {
  ifeq(a, b, options) {
    if (a == b) {
      return options.fn(this);}
    return options.inverse(this);
  },
};
        }

connect__handlebars --* main.hbs
main.hbs --* index.hbs
navbar.hbs --* index.hbs
head.hbs --* index.hbs
footer.hbs --* index.hbs
hbshelpers -left-* connect__handlebars


@enduml