@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300
 ComponentBackgroundColor DarkSlateGrey
}

skinparam usecase{
    FontColor<< UC5 >> green
    FontColor<< input >> Aqua
    FontColor<< textarea >> Aqua
    BackgroundColor<< validation >> red
}
component index.js {
    class staticFolder{
       app.use(express.static(path.join(__dirname, 'public')));
    }
}

component package.json {
    class scripts{
        "scripts": {
    "start": "node index.js",
    "build": "webpack -w",
    "dev": "nodemon index.js",
    "webapp:dev": "concurrently 'npm:build' 'npm:dev'",
    "lint": "eslint ./",
    "lint-fix": "eslint ./ --fix"
  },
    }
}
component webpack.config.js {
    class module{
        mode: 'development',
  devtool: 'source-map',
  context: path.resolve(__dirname, 'src'),
  entry: ['./main.js', './main.scss'],
  output: {
    path: path.resolve(__dirname, 'public'),
  },
  ..module rules..
  {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.(scss|css)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              reloadAll: true,
            },
          },
          'css-loader',
          'postcss-loader',
          'sass-loader',
        ],
      },
      ..plugins..
      new MinifyPlugin(
      {},
      {
        comments: false,}
    ),
    new MiniCssExtractPlugin({
      filename: '[name].css',
    }),
    }
}

component .babelrc {
    class presets{
        "@babel/preset-env"
    }
}
component .postcss.config.js {
    class postcss{
        ..plugins..
        require('autoprefixer'), 
        require('cssnano')
    }
}

package "src" {
    component main.scss{
    }
}

package "public" {
    component main.css{
    }
}
package "views"{
    package lauoyt{
         component main.hbs{
    }
    }
}

scripts --* webpack.config.js
webpack.config.js *--* .babelrc
postcss -left-* webpack.config.js
' module *-down-* src
module *-down-* staticFolder
staticFolder *--* src
main.scss -* main.css
main.css -down-* main.hbs

@enduml