@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
skinparam Shadowing false
skinparam Dpi 300
skinparam ComponentFontStyle red


class MyClass{
   - int count
   --
   # int number
..Strings..
   + String name
   --methods--
   ~ methodOne()
    methodTwo()
}

' - prived приватный
' # protected защищенный
' + public  публичный
' ~ package is protected защищенный пакет
note left: Это мой первый класс
class SecondClass{
    int aSecretField
    void secretMethod()
}
note left: Это секретный класс

class Free{
    int cout
}

MyClass o-- SecondClass
MyClass <-left- Free

' Стрелки 
' <--
' *--
' o--
' <.. ЧЕМ БОЛЬШЕ ТОЧЕК ТЕМ ДАЛЬШЕ РАССТОЯНИЕ
'


@enduml