@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
skinparam {
    Shadowing false
    Dpi 300
    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

package "public" #gray{
    class app{
        ..function..
        const toCurrency = (price) => {}
        return new Intl.NumberFormat('ru-RU', {}.format(price)
        currency: 'BYN',
        style: 'currency',

        const toDate = (date) => {}
        return new Intl.DateTimeFormat('ru-RU', {}).format(new Date(date));
        day: '2-digit',
        month: 'long',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',

        document.querySelectorAll('.price')
        document.querySelectorAll('.date')
        const $card = document.querySelector('#card')
        $card.addEventListener('click', (event) =>{}
        fetch('/card/remove/' + id, {}) .then((res) => res.json())
        .then((card) => {})
        if (card.courses.length){}
        return html({}).join('');
        $card.querySelector('tbody').innerHTML = html;
        $card.querySelector('.price').textContent = toCurrency(card.price);
        $card.innerHTML = '<p>Корзина пуста</p>';
        M.Tabs.init(document.querySelectorAll('.tabs'));

    }
}
package "partials" #gray{
    class footer{
        <script src="/app.js"></script>
    }
}

app --> footer

@enduml