@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300
    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red

}

package "routes" #gray{
    class profile{
        ..libraries..
        const { Router } = require('express');
        ..middleware..
        auth
        ..models..
        User
        ..function..
        router.get('/'):res.render('profile')
        router.post('/')
        const user = await User.findById(req.user._id);
        const toChange = req.body.name
        if (req.file): toChange.avatarUrl = req.file.path;
        Object.assign(user, toChange)
        await user.save();
        res.redirect('/profile');
    }
}
package "middleware" #gray{
    class middlewareAuth{
        ..module..
        module.exports = function (req, res, next)
        if (!req.session.isAuthenticated)
        return res.redirect('/auth/login');
    }

}
package "models" #gray{
    class User{
        ..libraries..
        mongoose: retern Schema, model
        ..userSchema..
        new Schema: return
        email: string
        name: string
        password: string
        avatarUrl: String
        resetToken: String
        resetTokenExp: Date

        cart: object
        items:array: retern
        count: number
        courseId: Schema.Types.ObjectId
        ref: Course
    }
}

User --> profile
profile  <-- middlewareAuth

@enduml