@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300

    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

skinparam usecase{
    FontColor<< UC5 >> green
    FontColor<< input >> Aqua
    FontColor<< textarea >> Aqua
    BackgroundColor<< validation >> red
}

actor "Пользователь" as UC7

usecase "Навигация" as navbar << UC5 >>
usecase "Добавить курс" as add__course
usecase "Подвал сайта" as footer__information << UC5 >>

usecase "Введите название курса" as name__course << input >>
usecase "Введите цену курса" as price__course << input >>
usecase "Введите url картинки" as url__course << input >>
usecase "Введите html описание курса" as textarea__course << textarea >>


usecase "Минимальная длинна названия 3 символа" as validation__name<< validation >>
usecase "Введите корректную цену" as validation__price<< validation >>
usecase "Введите корректный url картинки" as validation__url<< validation >>
usecase "Введите минимальное html описание курса" as validation__textarea<< validation >>

UC7 --> add__course
add__course -left-> navbar
add__course -right-> footer__information

add__course --> name__course
add__course --> price__course
add__course --> url__course
add__course --> textarea__course

name__course --> validation__name
price__course --> validation__price
url__course --> validation__url
textarea__course --> validation__textarea


@enduml