@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300

    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

skinparam usecase{
    FontColor<< UC5 >> green
     FontColor<< card_order >> Aqua
    FontColor<< button >> #3568b6
    FontColor<< price >> #9370DB
    BackgroundColor<< validation >> red
}

actor "Пользователь" as UC9


usecase "Навигация" as navbar << UC5 >>
usecase "Заказы" as orders
usecase "Подвал сайта" as footer__information << UC5 >>

usecase "Заказов нет" as no__order

usecase "Карта заказа" as card__order<< card_order >>
usecase "Заказ: id заказа" as id__order<< card_order >>
usecase "Дата и время заказа" as date__time__order<< card_order >>
usecase "Имя и email пользователя" as name__email__user<< card_order >>
usecase "Список, количество курсов" as list__count__courses<< card_order >>
usecase "Цена" as price<< price >>



UC9 --> orders
orders -left-> navbar
orders -right-> footer__information

orders --> card__order
orders -left-> no__order


card__order --> id__order
card__order --> date__time__order
card__order --> name__email__user
card__order --> list__count__courses

id__order --> price
date__time__order --> price
name__email__user --> price
list__count__courses --> price


@enduml