@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300

    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

skinparam usecase{
    FontColor<< ССылки >> yellow
}

actor "Зарегистрированный пользователь" as UC5


usecase "Навигация" as navbar
usecase "Главная страница" as main__page
usecase "Описание" as main__page__block
usecase "Подвал сайта" as footer__information

usecase "Магазин курсов" as shop__courses << ССылки >>
usecase "Главная" as main << ССылки >>
usecase "Курсы" as courses << ССылки >>
usecase "Добавить курс" as add__course << ССылки >>
usecase "Корзина" as cart << ССылки >>
usecase "Заказы" as orders << ССылки >>
usecase "Профиль" as profile << ССылки >>
usecase "Выйти" as exit << ССылки >>

usecase "Описание2" as main__page__block__2
usecase "Описание1" as main__page__block__1



usecase "Реквизиты1" as Requisites
usecase "Реквизиты2" as Requisites__1
usecase "Социальные иконки" as Social__links<< ССылки >>




UC5 --> main__page
main__page -down-> navbar
main__page -right-> main__page__block
main__page -left-> footer__information

navbar --> shop__courses
navbar --> main
navbar --> courses
navbar --> add__course
navbar --> cart
navbar --> orders
navbar --> profile
navbar --> exit


main__page__block --> main__page__block__1
main__page__block --> main__page__block__2


footer__information --> Requisites
footer__information --> Requisites__1
footer__information --> Social__links



@enduml