@startuml
!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam {
    Shadowing false
    Dpi 300

    ' classFontSize 40
    ' classAttributeFontSize 35
    ' PackageFontSize 50
    ' classAttributeFontStyle "Regular"
    ' classAttributeFontName  "Gill Sans"
    ' ClassAttributeFontColor red
}

skinparam usecase{
    FontColor<< UC5 >> green
    FontColor<< link >> yellow
    FontColor<< button >> #3568b6
}

actor "Пользователь" as UC6

usecase "Курсы не добавлены" as courses__zero

usecase "Страница курсов" as courses__page
usecase "Навигация" as navbar << UC5 >>
usecase "Карточка товара" as card 
usecase "Подвал сайта" as footer__information << UC5 >>


usecase "Открыть курс" as open << link >>>
usecase "Редактировать курс" as edit << link >>

usecase "Купить" as buy << button >>


UC6 --> courses__page
courses__page --> navbar
courses__page -left-> courses__zero
courses__page ---> card
courses__page --> footer__information

card -left-> open
card -down-> edit 
note left
Данная ссылка
видна только
владельцу курса
end note
card -right-> buy 
note right
Данная кнопка
видна только
авторизованным
пользователям
end note

@enduml